-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 11:57:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dashboard` DEFAULT CHARACTER SET utf8 ;
USE `dashboard` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `prefix` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `mobile` INT(12) NULL,
  `address` VARCHAR(45) NOT NULL,
  `house_number` VARCHAR(5) NOT NULL,
  `favorite` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groeps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard`.`groeps` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `favorite` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_x_groep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard`.`student_x_groep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `students_id` INT NOT NULL,
  `groeps_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_x_groep_students_idx` (`students_id` ASC),
  INDEX `fk_student_x_groep_groeps1_idx` (`groeps_id` ASC),
  CONSTRAINT `fk_student_x_groep_students`
    FOREIGN KEY (`students_id`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_x_groep_groeps1`
    FOREIGN KEY (`groeps_id`)
    REFERENCES `mydb`.`groeps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
